module.exports = {
  someSidebar: {
    GettingStarted: ["getting-started/overview"],
    Foundations: [
      "foundation/Color",
      "foundation/Typography",
      "foundation/Patterns",
    ],
    Components: [
      "component-docs/Accordion",
      "component-docs/Alert",
      "component-docs/Avatar",
      "component-docs/Badge",
      "component-docs/Button",
      "component-docs/Card",
      "component-docs/Checkbox",
      "component-docs/DatePicker",
      "component-docs/Input",
      "component-docs/Modal",
      "component-docs/Pagination",
      "component-docs/Popover",
      "component-docs/Radio",
      "component-docs/Select",
      "component-docs/SideSheet",
      "component-docs/Spinner",
      "component-docs/Tab",
      "component-docs/Table",
      "component-docs/TextArea",
      "component-docs/TimePicker",
      "component-docs/Toast",
      "component-docs/ToolTip",
    ],
  },
};
